services:
  - type: web
    name: or-scheduling-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt && cd frontend && npm ci && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3

